### ISSUE TITLE
Reconsider Licensing

### ISSUE THREAD

**Issue by doggan** [doggan/diablogl#1]
Reference:
https://github.com/doggan/diablogl/commit/2421390898621f495ac730735b15bd61e0c779c8#commitcomment-9211916

**Comment by doggan** [comment]
Changed to MIT (https://github.com/doggan/diablogl/commit/6e730a2f7cd0bfe67eb8c6f81092a7d861c48ec7).

**Comment by mewmew** [comment]
Thanks for giving this some thought! :)

**Comment by ghost** [comment]
How can u change it to MIT when the .mpq files are still owned by Blizzard?

**Comment by doggan** [comment]
MPQ data/files have never been, and never will be distributed by this project.

This project is only gameplay code. The actual data (MPQ file) must be supplied by the user after having legally purchased the original game.
